### ISSUE TITLE
Update from Black Computer

### ISSUE THREAD

**Issue by gmartinez123456** [cloud5678/cloud5678-2015#1]
Old Code

**Comment by mason2smart** [comment]
Black computer?????

On Monday, April 13, 2015, Gilbert Martinez notifications@github.com
wrote:

> Old Code
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cloud5678/cloud5678-2015/issues/1.

## 

Mason

**Comment by gmartinez123456** [comment]
My personal one, using seth's right now
